# Generated by Django 2.2.7 on 2019-11-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedroom', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('garage', models.PositiveIntegerField()),
                ('photo_main', models.ImageField(upload_to='photos')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Category')),
            ],
        ),
    ]
