# Generated by Django 2.2.7 on 2019-11-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
